/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm.oce.peps.vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ariel
 */
public class VistaPEPS extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPEPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Principal = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jL_Contabilidad = new javax.swing.JLabel();
        jL_Productos = new javax.swing.JLabel();
        jCB_Productos = new javax.swing.JComboBox<>();
        jB_Cargar = new javax.swing.JButton();
        jB_Crear = new javax.swing.JButton();
        jP_Producto = new javax.swing.JPanel();
        jL_Stock = new javax.swing.JLabel();
        jL_Precio = new javax.swing.JLabel();
        jTF_Stock = new javax.swing.JTextField();
        jTF_Precio = new javax.swing.JTextField();
        jL_FechaActual = new javax.swing.JLabel();
        jL_VentaMes = new javax.swing.JLabel();
        jL_VentaTotal = new javax.swing.JLabel();
        jTF_VentaMes = new javax.swing.JTextField();
        jTF_VentaTotal = new javax.swing.JTextField();
        jL_Resumen = new javax.swing.JLabel();
        jCB_Fecha = new javax.swing.JComboBox<>();
        jB_CargarFecha = new javax.swing.JButton();
        jP_Registro = new javax.swing.JPanel();
        jL_NuevoRegistro = new javax.swing.JLabel();
        jTF_PrecioUR = new javax.swing.JTextField();
        jC_PrecioUR = new javax.swing.JCheckBox();
        jTF_UnidadesR = new javax.swing.JTextField();
        jL_PrecioUnitarioR = new javax.swing.JLabel();
        jL_UnidadesR = new javax.swing.JLabel();
        jB_Registrar = new javax.swing.JButton();
        jP_Salida = new javax.swing.JPanel();
        jL_UnidadesS = new javax.swing.JLabel();
        jTF_UnidadesS = new javax.swing.JTextField();
        jL_Salida = new javax.swing.JLabel();
        jB_Salida = new javax.swing.JButton();
        jL_FechaValor = new javax.swing.JLabel();
        jL_Fecha = new javax.swing.JLabel();
        jL_NuevoProducto = new javax.swing.JLabel();
        jTF_NuevoProducto = new javax.swing.JTextField();
        jL_Seleccion = new javax.swing.JLabel();
        jP_Menu = new javax.swing.JPanel();
        jL_Salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(577, 497));
        setMinimumSize(new java.awt.Dimension(577, 497));
        setUndecorated(true);
        setResizable(false);

        jP_Principal.setBackground(new java.awt.Color(25, 42, 86));
        jP_Principal.setMaximumSize(new java.awt.Dimension(580, 497));
        jP_Principal.setMinimumSize(new java.awt.Dimension(580, 497));

        jL_Titulo.setBackground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setFont(new java.awt.Font("Anton", 0, 36)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setText("STOCK");

        jL_Contabilidad.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Contabilidad.setForeground(new java.awt.Color(236, 240, 241));
        jL_Contabilidad.setText("Proyecto Contabilidad 2020");

        jL_Productos.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Productos.setForeground(new java.awt.Color(255, 255, 255));
        jL_Productos.setText("Producto");

        jCB_Productos.setBackground(new java.awt.Color(25, 42, 86));

        jB_Cargar.setText("Cargar");

        jB_Crear.setText("Crear");

        jP_Producto.setBackground(new java.awt.Color(39, 60, 117));

        jL_Stock.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jL_Stock.setText("Disponibilidad");

        jL_Precio.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_Precio.setForeground(new java.awt.Color(255, 255, 255));
        jL_Precio.setText("Precio");

        jTF_Stock.setEditable(false);
        jTF_Stock.setBackground(new java.awt.Color(25, 42, 86));
        jTF_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jTF_Stock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTF_Precio.setEditable(false);
        jTF_Precio.setBackground(new java.awt.Color(25, 42, 86));
        jTF_Precio.setForeground(new java.awt.Color(255, 255, 255));
        jTF_Precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jL_FechaActual.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_FechaActual.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaActual.setText("Fecha");

        jL_VentaMes.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_VentaMes.setForeground(new java.awt.Color(255, 255, 255));
        jL_VentaMes.setText("Venta | Mes");

        jL_VentaTotal.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_VentaTotal.setForeground(new java.awt.Color(255, 255, 255));
        jL_VentaTotal.setText("Venta | Total");

        jTF_VentaMes.setEditable(false);
        jTF_VentaMes.setBackground(new java.awt.Color(25, 42, 86));
        jTF_VentaMes.setForeground(new java.awt.Color(255, 255, 255));
        jTF_VentaMes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_VentaMes.setCaretColor(new java.awt.Color(255, 255, 255));

        jTF_VentaTotal.setEditable(false);
        jTF_VentaTotal.setBackground(new java.awt.Color(25, 42, 86));
        jTF_VentaTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTF_VentaTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jL_Resumen.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_Resumen.setForeground(new java.awt.Color(255, 255, 255));
        jL_Resumen.setText("Resumen General");

        jCB_Fecha.setBackground(new java.awt.Color(25, 42, 86));
        jCB_Fecha.setForeground(new java.awt.Color(255, 255, 255));

        jB_CargarFecha.setText("Ver");

        javax.swing.GroupLayout jP_ProductoLayout = new javax.swing.GroupLayout(jP_Producto);
        jP_Producto.setLayout(jP_ProductoLayout);
        jP_ProductoLayout.setHorizontalGroup(
            jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ProductoLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jL_FechaActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_CargarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ProductoLayout.createSequentialGroup()
                        .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_ProductoLayout.createSequentialGroup()
                                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jL_VentaTotal)
                                    .addComponent(jL_VentaMes)
                                    .addComponent(jL_Stock)
                                    .addComponent(jL_Precio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTF_VentaMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(jTF_Precio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Stock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_VentaTotal)))
                            .addComponent(jL_Resumen))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_ProductoLayout.setVerticalGroup(
            jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Resumen)
                .addGap(18, 18, 18)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_CargarFecha)
                    .addComponent(jL_FechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Stock)
                    .addComponent(jTF_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Precio)
                    .addComponent(jTF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_VentaMes)
                    .addComponent(jTF_VentaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_VentaTotal)
                    .addComponent(jTF_VentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jP_Registro.setBackground(new java.awt.Color(39, 60, 117));
        jP_Registro.setMaximumSize(new java.awt.Dimension(280, 169));
        jP_Registro.setMinimumSize(new java.awt.Dimension(280, 169));

        jL_NuevoRegistro.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_NuevoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jL_NuevoRegistro.setText("Nuevo Registro");

        jTF_PrecioUR.setEditable(false);
        jTF_PrecioUR.setBackground(new java.awt.Color(25, 42, 86));
        jTF_PrecioUR.setForeground(new java.awt.Color(255, 255, 255));
        jTF_PrecioUR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jC_PrecioUR.setBackground(new java.awt.Color(52, 73, 94));
        jC_PrecioUR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jC_PrecioUR.setForeground(new java.awt.Color(255, 255, 255));

        jTF_UnidadesR.setBackground(new java.awt.Color(25, 42, 86));
        jTF_UnidadesR.setForeground(new java.awt.Color(255, 255, 255));
        jTF_UnidadesR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jL_PrecioUnitarioR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_PrecioUnitarioR.setForeground(new java.awt.Color(255, 255, 255));
        jL_PrecioUnitarioR.setText("Precio Unitario");

        jL_UnidadesR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_UnidadesR.setForeground(new java.awt.Color(255, 255, 255));
        jL_UnidadesR.setText("Unidades");

        jB_Registrar.setText("Registrar");

        javax.swing.GroupLayout jP_RegistroLayout = new javax.swing.GroupLayout(jP_Registro);
        jP_Registro.setLayout(jP_RegistroLayout);
        jP_RegistroLayout.setHorizontalGroup(
            jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_RegistroLayout.createSequentialGroup()
                        .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_UnidadesR)
                            .addComponent(jL_PrecioUnitarioR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jB_Registrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTF_UnidadesR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_RegistroLayout.createSequentialGroup()
                                .addComponent(jTF_PrecioUR, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jC_PrecioUR))))
                    .addComponent(jL_NuevoRegistro))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jP_RegistroLayout.setVerticalGroup(
            jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_NuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_PrecioUR)
                    .addComponent(jC_PrecioUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_PrecioUnitarioR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_UnidadesR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_UnidadesR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Registrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jP_Salida.setBackground(new java.awt.Color(39, 60, 117));
        jP_Salida.setMaximumSize(new java.awt.Dimension(264, 132));
        jP_Salida.setMinimumSize(new java.awt.Dimension(264, 132));

        jL_UnidadesS.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_UnidadesS.setForeground(new java.awt.Color(255, 255, 255));
        jL_UnidadesS.setText("Unidades");

        jTF_UnidadesS.setBackground(new java.awt.Color(25, 42, 86));
        jTF_UnidadesS.setForeground(new java.awt.Color(255, 255, 255));
        jTF_UnidadesS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jL_Salida.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_Salida.setForeground(new java.awt.Color(255, 255, 255));
        jL_Salida.setText("Salida");

        jB_Salida.setText("Enviar Salida");

        javax.swing.GroupLayout jP_SalidaLayout = new javax.swing.GroupLayout(jP_Salida);
        jP_Salida.setLayout(jP_SalidaLayout);
        jP_SalidaLayout.setHorizontalGroup(
            jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_UnidadesS)
                    .addComponent(jL_Salida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_UnidadesS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_SalidaLayout.setVerticalGroup(
            jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalidaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jL_Salida)
                .addGap(18, 18, 18)
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_UnidadesS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_UnidadesS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Salida)
                .addGap(17, 17, 17))
        );

        jL_FechaValor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_FechaValor.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaValor.setText("15/11/2020");

        jL_Fecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        jL_Fecha.setText("Fecha:");

        jL_NuevoProducto.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_NuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        jL_NuevoProducto.setText("Nombre");

        jTF_NuevoProducto.setBackground(new java.awt.Color(25, 42, 86));

        jL_Seleccion.setFont(new java.awt.Font("Open Sans Condensed", 0, 12)); // NOI18N
        jL_Seleccion.setForeground(new java.awt.Color(236, 240, 241));
        jL_Seleccion.setText("Producto actual: Nombre del producto");

        jP_Menu.setBackground(new java.awt.Color(39, 60, 117));
        jP_Menu.setMaximumSize(new java.awt.Dimension(0, 42));
        jP_Menu.setMinimumSize(new java.awt.Dimension(0, 42));

        jL_Salir.setBackground(new java.awt.Color(222, 222, 222));
        jL_Salir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jL_Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Salir.setText("X");
        jL_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_MenuLayout = new javax.swing.GroupLayout(jP_Menu);
        jP_Menu.setLayout(jP_MenuLayout);
        jP_MenuLayout.setHorizontalGroup(
            jP_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_MenuLayout.setVerticalGroup(
            jP_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Salir)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_PrincipalLayout = new javax.swing.GroupLayout(jP_Principal);
        jP_Principal.setLayout(jP_PrincipalLayout);
        jP_PrincipalLayout.setHorizontalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                                .addComponent(jL_Contabilidad)
                                .addGap(128, 128, 128)
                                .addComponent(jL_Fecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_FechaValor))
                            .addComponent(jL_Titulo)))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_NuevoProducto)
                            .addComponent(jL_Productos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTF_NuevoProducto)
                                    .addComponent(jCB_Productos, 0, 432, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_Cargar)))))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jP_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jP_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_Salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jP_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_PrincipalLayout.setVerticalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PrincipalLayout.createSequentialGroup()
                .addComponent(jP_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_NuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_NuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_Crear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Cargar)
                    .addComponent(jCB_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Productos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Seleccion)
                .addGap(13, 13, 13)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jP_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Titulo))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jP_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Contabilidad)
                    .addComponent(jL_FechaValor)
                    .addComponent(jL_Fecha))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jL_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println("Hello");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPEPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPEPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPEPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPEPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cargar;
    private javax.swing.JButton jB_CargarFecha;
    private javax.swing.JButton jB_Crear;
    private javax.swing.JButton jB_Registrar;
    private javax.swing.JButton jB_Salida;
    private javax.swing.JComboBox<String> jCB_Fecha;
    private javax.swing.JComboBox<String> jCB_Productos;
    private javax.swing.JCheckBox jC_PrecioUR;
    private javax.swing.JLabel jL_Contabilidad;
    private javax.swing.JLabel jL_Fecha;
    private javax.swing.JLabel jL_FechaActual;
    private javax.swing.JLabel jL_FechaValor;
    private javax.swing.JLabel jL_NuevoProducto;
    private javax.swing.JLabel jL_NuevoRegistro;
    private javax.swing.JLabel jL_Precio;
    private javax.swing.JLabel jL_PrecioUnitarioR;
    private javax.swing.JLabel jL_Productos;
    private javax.swing.JLabel jL_Resumen;
    private javax.swing.JLabel jL_Salida;
    private javax.swing.JLabel jL_Salir;
    private javax.swing.JLabel jL_Seleccion;
    private javax.swing.JLabel jL_Stock;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jL_UnidadesR;
    private javax.swing.JLabel jL_UnidadesS;
    private javax.swing.JLabel jL_VentaMes;
    private javax.swing.JLabel jL_VentaTotal;
    private javax.swing.JPanel jP_Menu;
    private javax.swing.JPanel jP_Principal;
    private javax.swing.JPanel jP_Producto;
    private javax.swing.JPanel jP_Registro;
    private javax.swing.JPanel jP_Salida;
    private javax.swing.JTextField jTF_NuevoProducto;
    private javax.swing.JTextField jTF_Precio;
    private javax.swing.JTextField jTF_PrecioUR;
    private javax.swing.JTextField jTF_Stock;
    private javax.swing.JTextField jTF_UnidadesR;
    private javax.swing.JTextField jTF_UnidadesS;
    private javax.swing.JTextField jTF_VentaMes;
    private javax.swing.JTextField jTF_VentaTotal;
    // End of variables declaration//GEN-END:variables

    public JButton getjB_Cargar() {
        return jB_Cargar;
    }

    public void setjB_Cargar(JButton jB_Cargar) {
        this.jB_Cargar = jB_Cargar;
    }

    public JButton getjB_CargarFecha() {
        return jB_CargarFecha;
    }

    public void setjB_CargarFecha(JButton jB_CargarFecha) {
        this.jB_CargarFecha = jB_CargarFecha;
    }

    public JButton getjB_Crear() {
        return jB_Crear;
    }

    public void setjB_Crear(JButton jB_Crear) {
        this.jB_Crear = jB_Crear;
    }

    public JButton getjB_Registrar() {
        return jB_Registrar;
    }

    public void setjB_Registrar(JButton jB_Registrar) {
        this.jB_Registrar = jB_Registrar;
    }

    public JButton getjB_Salida() {
        return jB_Salida;
    }

    public void setjB_Salida(JButton jB_Salida) {
        this.jB_Salida = jB_Salida;
    }

    public JComboBox<String> getjCB_Fecha() {
        return jCB_Fecha;
    }

    public void setjCB_Fecha(JComboBox<String> jCB_Fecha) {
        this.jCB_Fecha = jCB_Fecha;
    }

    public JComboBox<String> getjCB_Productos() {
        return jCB_Productos;
    }

    public void setjCB_Productos(JComboBox<String> jCB_Productos) {
        this.jCB_Productos = jCB_Productos;
    }

    public JCheckBox getjC_PrecioUR() {
        return jC_PrecioUR;
    }

    public void setjC_PrecioUR(JCheckBox jC_PrecioUR) {
        this.jC_PrecioUR = jC_PrecioUR;
    }

    public JLabel getjL_Contabilidad() {
        return jL_Contabilidad;
    }

    public void setjL_Contabilidad(JLabel jL_Contabilidad) {
        this.jL_Contabilidad = jL_Contabilidad;
    }

    public JLabel getjL_Contabilidad1() {
        return jL_Contabilidad;
    }

    public void setjL_Contabilidad1(JLabel jL_Contabilidad1) {
        this.jL_Contabilidad = jL_Contabilidad1;
    }

    public JLabel getjL_Fecha() {
        return jL_Fecha;
    }

    public void setjL_Fecha(JLabel jL_Fecha) {
        this.jL_Fecha = jL_Fecha;
    }

    public JLabel getjL_FechaActual() {
        return jL_FechaActual;
    }

    public void setjL_FechaActual(JLabel jL_FechaActual) {
        this.jL_FechaActual = jL_FechaActual;
    }

    public JLabel getjL_FechaValor() {
        return jL_FechaValor;
    }

    public void setjL_FechaValor(JLabel jL_FechaValor) {
        this.jL_FechaValor = jL_FechaValor;
    }

    public JLabel getjL_NuevoProducto() {
        return jL_NuevoProducto;
    }

    public void setjL_NuevoProducto(JLabel jL_NuevoProducto) {
        this.jL_NuevoProducto = jL_NuevoProducto;
    }

    public JLabel getjL_NuevoRegistro() {
        return jL_NuevoRegistro;
    }

    public void setjL_NuevoRegistro(JLabel jL_NuevoRegistro) {
        this.jL_NuevoRegistro = jL_NuevoRegistro;
    }

    public JLabel getjL_Precio() {
        return jL_Precio;
    }

    public void setjL_Precio(JLabel jL_Precio) {
        this.jL_Precio = jL_Precio;
    }

    public JLabel getjL_PrecioUnitarioR() {
        return jL_PrecioUnitarioR;
    }

    public void setjL_PrecioUnitarioR(JLabel jL_PrecioUnitarioR) {
        this.jL_PrecioUnitarioR = jL_PrecioUnitarioR;
    }

    public JLabel getjL_Productos() {
        return jL_Productos;
    }

    public void setjL_Productos(JLabel jL_Productos) {
        this.jL_Productos = jL_Productos;
    }

    public JLabel getjL_Resumen() {
        return jL_Resumen;
    }

    public void setjL_Resumen(JLabel jL_Resumen) {
        this.jL_Resumen = jL_Resumen;
    }

    public JLabel getjL_Salida() {
        return jL_Salida;
    }

    public void setjL_Salida(JLabel jL_Salida) {
        this.jL_Salida = jL_Salida;
    }

    public JLabel getjL_Stock() {
        return jL_Stock;
    }

    public void setjL_Stock(JLabel jL_Stock) {
        this.jL_Stock = jL_Stock;
    }

    public JLabel getjL_Titulo() {
        return jL_Titulo;
    }

    public void setjL_Titulo(JLabel jL_Titulo) {
        this.jL_Titulo = jL_Titulo;
    }

    public JLabel getjL_UnidadesR() {
        return jL_UnidadesR;
    }

    public void setjL_UnidadesR(JLabel jL_UnidadesR) {
        this.jL_UnidadesR = jL_UnidadesR;
    }

    public JLabel getjL_UnidadesS() {
        return jL_UnidadesS;
    }

    public void setjL_UnidadesS(JLabel jL_UnidadesS) {
        this.jL_UnidadesS = jL_UnidadesS;
    }

    public JLabel getjL_VentaMes() {
        return jL_VentaMes;
    }

    public void setjL_VentaMes(JLabel jL_VentaMes) {
        this.jL_VentaMes = jL_VentaMes;
    }

    public JLabel getjL_VentaTotal() {
        return jL_VentaTotal;
    }

    public void setjL_VentaTotal(JLabel jL_VentaTotal) {
        this.jL_VentaTotal = jL_VentaTotal;
    }

    public JPanel getjP_Principal() {
        return jP_Principal;
    }

    public void setjP_Principal(JPanel jP_Principal) {
        this.jP_Principal = jP_Principal;
    }

    public JPanel getjP_Producto() {
        return jP_Producto;
    }

    public void setjP_Producto(JPanel jP_Producto) {
        this.jP_Producto = jP_Producto;
    }

    public JPanel getjP_Registro() {
        return jP_Registro;
    }

    public void setjP_Registro(JPanel jP_Registro) {
        this.jP_Registro = jP_Registro;
    }

    public JPanel getjP_Salida() {
        return jP_Salida;
    }

    public void setjP_Salida(JPanel jP_Salida) {
        this.jP_Salida = jP_Salida;
    }

    public JTextField getjTF_NuevoProducto() {
        return jTF_NuevoProducto;
    }

    public void setjTF_NuevoProducto(JTextField jTF_NuevoProducto) {
        this.jTF_NuevoProducto = jTF_NuevoProducto;
    }

    public JTextField getjTF_Precio() {
        return jTF_Precio;
    }

    public void setjTF_Precio(JTextField jTF_Precio) {
        this.jTF_Precio = jTF_Precio;
    }

    public JTextField getjTF_PrecioUR() {
        return jTF_PrecioUR;
    }

    public void setjTF_PrecioUR(JTextField jTF_PrecioUR) {
        this.jTF_PrecioUR = jTF_PrecioUR;
    }

    public JTextField getjTF_Stock() {
        return jTF_Stock;
    }

    public void setjTF_Stock(JTextField jTF_Stock) {
        this.jTF_Stock = jTF_Stock;
    }

    public JTextField getjTF_UnidadesR() {
        return jTF_UnidadesR;
    }

    public void setjTF_UnidadesR(JTextField jTF_UnidadesR) {
        this.jTF_UnidadesR = jTF_UnidadesR;
    }

    public JTextField getjTF_UnidadesS() {
        return jTF_UnidadesS;
    }

    public void setjTF_UnidadesS(JTextField jTF_UnidadesS) {
        this.jTF_UnidadesS = jTF_UnidadesS;
    }

    public JTextField getjTF_VentaMes() {
        return jTF_VentaMes;
    }

    public void setjTF_VentaMes(JTextField jTF_VentaMes) {
        this.jTF_VentaMes = jTF_VentaMes;
    }

    public JTextField getjTF_VentaTotal() {
        return jTF_VentaTotal;
    }

    public void setjTF_VentaTotal(JTextField jTF_VentaTotal) {
        this.jTF_VentaTotal = jTF_VentaTotal;
    }

    public JLabel getjL_Seleccion() {
        return jL_Seleccion;
    }

    public void setjL_Seleccion(JLabel jL_Seleccion) {
        this.jL_Seleccion = jL_Seleccion;
    }

    public JPanel getjP_Menu() {
        return jP_Menu;
    }

    public void setjP_Menu(JPanel jP_Menu) {
        this.jP_Menu = jP_Menu;
    }
}
